# Generated by Django 2.1.7 on 2019-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('desc', models.TextField(default=models.CharField(max_length=255, verbose_name='Название мероприятия'), verbose_name='Описание')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_time', models.DateTimeField(verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрытый?(False-нет, True-да)')),
            ],
        ),
    ]
