# Generated by Django 2.1.7 on 2019-03-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_auto_20190330_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(default=424, on_delete=django.db.models.deletion.CASCADE, to='heart.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Zadacha', max_length=255, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='todo',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='event', max_length=255, verbose_name='Название мероприятия'),
        ),
    ]
