# Generated by Django 2.1.7 on 2019-03-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_auto_20190330_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.Event')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart.Task')),
            ],
        ),
    ]
