# Generated by Django 2.1.7 on 2019-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(default='ничего', max_length=255, verbose_name='Тэги(через запятую)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=models.CharField(default='ничего', max_length=255, verbose_name='Тэги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя партнера'),
        ),
    ]
