# Generated by Django 2.1.7 on 2019-03-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='event',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='task',
        ),
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heart.Partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(default=1, max_length=255, verbose_name='Тэги(через запятую)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='partner',
            name='mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=models.CharField(default=1, max_length=255, verbose_name='Тэги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, verbose_name='телефон партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='web',
            field=models.CharField(blank=True, max_length=255, verbose_name='web-сайт'),
        ),
        migrations.AddField(
            model_name='task',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heart.Partner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя партнера'),
        ),
    ]
