# Generated by Django 2.1.7 on 2019-03-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0009_auto_20190330_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='inn',
            field=models.CharField(default='inn', max_length=255, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='mail',
            field=models.CharField(default='example@mail.ru', max_length=255, verbose_name='Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='telephone',
            field=models.CharField(default='your number', max_length=255, verbose_name='телефон партнёра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='web',
            field=models.CharField(default='site.ru', max_length=255, verbose_name='web-сайт'),
            preserve_default=False,
        ),
    ]
