# Generated by Django 2.1.7 on 2019-03-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0009_auto_20190331_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО/ЮР. Лицо'),
        ),
    ]
