# Generated by Django 2.1.7 on 2019-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_auto_20190331_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('ST', 'НАЧАТА'), ('DO', 'В ПРОЦЕССЕ'), ('EN', 'ЗАВЕРШЕНА')], default='ST', max_length=2, verbose_name='Прогресс'),
        ),
    ]
