# Generated by Django 2.1.7 on 2019-03-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_auto_20190330_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='heart.Task'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, verbose_name='телефон партнёра'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='web',
            field=models.CharField(blank=True, max_length=255, verbose_name='web-сайт'),
        ),
    ]
