# Generated by Django 2.1.7 on 2019-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0011_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.TextField(blank=True, verbose_name='Опишите взаимоотношения с партнёром.'),
        ),
    ]
