# Generated by Django 2.1.7 on 2019-03-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0012_partner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон партнёра'),
        ),
    ]
